services:

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - server

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    environment:
      - REDISINSIGHT_REDIS_HOST=redis
      - REDISINSIGHT_REDIS_PORT=6379
      - REDISINSIGHT_REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    networks:
      - server


volumes:
  postgres_data:
  redis_data:
  redis_insight_data:

networks:
  server:

